#!/usr/bin/env bash

check-err() {
    local CODE=$?
    local MSG="$1"
    if [ $CODE -ne 0 ] ; then
        echo ERROR: "$MSG"
        exit 1
    fi
}

echo "--------------------------------"
echo "Submodules: git add"
echo "--------------------------------"
git submodule foreach git add .
check-err "Adding to submodules."

echo

echo "--------------------------------"
echo "Main: git add"
echo "--------------------------------"
git add .
check-err "Adding to main."

