#!/usr/bin/env bash

check-err() {
    local CODE=$?
    local MSG="$1"
    if [ $CODE -ne 0 ] ; then
        echo ERROR: "$MSG"
        exit 1
    fi
}

PUSH_IT='
    if [ `git log origin..HEAD --oneline | wc -l` -ne 0 ] ; then
        git push
    fi
'

echo "--------------------------------"
echo "Submodules: git push"
echo "--------------------------------"
git submodule foreach "${PUSH_IT}"
check-err "Pushing submodules"

echo

echo "--------------------------------"
echo "Main: git push"
echo "--------------------------------"
eval "${PUSH_IT}"
check-err "Pushing main"

