<?php
/**
 * ExecInputTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  SingleStore
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SingleStore HTTP API Spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace SingleStore\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ExecInputTest Class Doc Comment
 *
 * @category    Class
 * @description ExecInput
 * @package     SingleStore
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ExecInputTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ExecInput"
     */
    public function testExecInput()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sql"
     */
    public function testPropertySql()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "args"
     */
    public function testPropertyArgs()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "database"
     */
    public function testPropertyDatabase()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
