<?php
/**
 * QueryInputTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  SingleStore
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SingleStore HTTP API Spec
 *
 * This API allows you to execute SQL statements against a SingleStore database.  It supports all statements that can be run in a direct database connection, and uses conventional data type conversion.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace SingleStore\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * QueryInputTest Class Doc Comment
 *
 * @category    Class
 * @description QueryInput
 * @package     SingleStore
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class QueryInputTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "QueryInput"
     */
    public function testQueryInput()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sql"
     */
    public function testPropertySql()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "args"
     */
    public function testPropertyArgs()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "database"
     */
    public function testPropertyDatabase()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
